# Generated by Django 5.1.4 on 2024-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "mail",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("phNo", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=6)),
                ("program", models.CharField(max_length=20)),
                ("route", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "mail",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("seats", models.IntegerField()),
                ("regNo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SignUP",
            fields=[
                (
                    "mail",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
                ("phNo", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=6)),
                ("program", models.CharField(max_length=20)),
                ("route", models.JSONField()),
            ],
        ),
    ]
