# Generated by Django 5.1.4 on 2024-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeuser",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="signup",
            name="rating",
            field=models.FloatField(null=True),
        ),
    ]
