# Generated by Django 5.1.4 on 2024-12-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_activeuser_rating_signup_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderAccept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corider_name", models.CharField(max_length=30)),
                ("corider_mail", models.CharField(max_length=30)),
                ("corider_gender", models.CharField(max_length=6)),
                ("corider_phNo", models.CharField(max_length=10)),
                ("corider_gate", models.IntegerField()),
                ("corider_dest", models.CharField(max_length=30)),
                ("rider_mail", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="RideStarted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rider_mail", models.CharField(max_length=30)),
                ("corider_mail", models.CharField(max_length=30)),
                ("rider_phNo", models.CharField(max_length=30)),
                ("corider_phNo", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="activeuser",
            name="program",
        ),
        migrations.AddField(
            model_name="activeuser",
            name="gate",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="signup",
            name="rides",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="activeuser",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="signup",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
